/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BinaryMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "FEE_BPS"
      | "OUTCOME_NO"
      | "OUTCOME_YES"
      | "addLiquidity"
      | "buyNo"
      | "buyYes"
      | "closeTime"
      | "collateral"
      | "getSpotPriceNoE18"
      | "getSpotPriceYesE18"
      | "merge"
      | "noBalance"
      | "noReserve"
      | "owner"
      | "question"
      | "redeem"
      | "redeemPool"
      | "renounceOwnership"
      | "resolve"
      | "resolved"
      | "split"
      | "swapNoForYes"
      | "swapYesForNo"
      | "transferOwnership"
      | "winningOutcome"
      | "yesBalance"
      | "yesReserve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "Merge"
      | "OwnershipTransferred"
      | "PoolRedeemed"
      | "Redeemed"
      | "Resolved"
      | "Split"
      | "Swap"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "OUTCOME_NO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OUTCOME_YES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyYes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "closeTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotPriceNoE18",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotPriceYesE18",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "merge", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "noBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "noReserve", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "question", values?: undefined): string;
  encodeFunctionData(functionFragment: "redeem", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "resolved", values?: undefined): string;
  encodeFunctionData(functionFragment: "split", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "swapNoForYes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapYesForNo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "winningOutcome",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yesBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "yesReserve",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OUTCOME_NO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "OUTCOME_YES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyYes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "collateral", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSpotPriceNoE18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpotPriceYesE18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "question", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapNoForYes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapYesForNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yesBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yesReserve", data: BytesLike): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    collateralIn: BigNumberish,
    yesAdded: BigNumberish,
    noAdded: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    collateralIn: bigint,
    yesAdded: bigint,
    noAdded: bigint
  ];
  export interface OutputObject {
    provider: string;
    collateralIn: bigint;
    yesAdded: bigint;
    noAdded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MergeEvent {
  export type InputTuple = [
    user: AddressLike,
    sharesBurnedEach: BigNumberish,
    collateralOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    sharesBurnedEach: bigint,
    collateralOut: bigint
  ];
  export interface OutputObject {
    user: string;
    sharesBurnedEach: bigint;
    collateralOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolRedeemedEvent {
  export type InputTuple = [
    to: AddressLike,
    winningOutcome: BigNumberish,
    sharesBurned: BigNumberish,
    collateralOut: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    winningOutcome: bigint,
    sharesBurned: bigint,
    collateralOut: bigint
  ];
  export interface OutputObject {
    to: string;
    winningOutcome: bigint;
    sharesBurned: bigint;
    collateralOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    user: AddressLike,
    winningOutcome: BigNumberish,
    sharesBurned: BigNumberish,
    collateralOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    winningOutcome: bigint,
    sharesBurned: bigint,
    collateralOut: bigint
  ];
  export interface OutputObject {
    user: string;
    winningOutcome: bigint;
    sharesBurned: bigint;
    collateralOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolvedEvent {
  export type InputTuple = [winningOutcome: BigNumberish];
  export type OutputTuple = [winningOutcome: bigint];
  export interface OutputObject {
    winningOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitEvent {
  export type InputTuple = [
    user: AddressLike,
    collateralIn: BigNumberish,
    sharesMintedEach: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    collateralIn: bigint,
    sharesMintedEach: bigint
  ];
  export interface OutputObject {
    user: string;
    collateralIn: bigint;
    sharesMintedEach: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    user: AddressLike,
    inOutcome: BigNumberish,
    amountIn: BigNumberish,
    outOutcome: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    inOutcome: bigint,
    amountIn: bigint,
    outOutcome: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    user: string;
    inOutcome: bigint;
    amountIn: bigint;
    outOutcome: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BinaryMarket extends BaseContract {
  connect(runner?: ContractRunner | null): BinaryMarket;
  waitForDeployment(): Promise<this>;

  interface: BinaryMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  OUTCOME_NO: TypedContractMethod<[], [bigint], "view">;

  OUTCOME_YES: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [collateralAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyNo: TypedContractMethod<
    [collateralIn: BigNumberish, minTotalNoOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  buyYes: TypedContractMethod<
    [collateralIn: BigNumberish, minTotalYesOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  closeTime: TypedContractMethod<[], [bigint], "view">;

  collateral: TypedContractMethod<[], [string], "view">;

  getSpotPriceNoE18: TypedContractMethod<[], [bigint], "view">;

  getSpotPriceYesE18: TypedContractMethod<[], [bigint], "view">;

  merge: TypedContractMethod<[amountEach: BigNumberish], [void], "nonpayable">;

  noBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  noReserve: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  question: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<[], [void], "nonpayable">;

  redeemPool: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolve: TypedContractMethod<[outcome: BigNumberish], [void], "nonpayable">;

  resolved: TypedContractMethod<[], [boolean], "view">;

  split: TypedContractMethod<
    [collateralAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapNoForYes: TypedContractMethod<
    [noIn: BigNumberish, minYesOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapYesForNo: TypedContractMethod<
    [yesIn: BigNumberish, minNoOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  winningOutcome: TypedContractMethod<[], [bigint], "view">;

  yesBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  yesReserve: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OUTCOME_NO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OUTCOME_YES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [collateralAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyNo"
  ): TypedContractMethod<
    [collateralIn: BigNumberish, minTotalNoOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyYes"
  ): TypedContractMethod<
    [collateralIn: BigNumberish, minTotalYesOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateral"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSpotPriceNoE18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSpotPriceYesE18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merge"
  ): TypedContractMethod<[amountEach: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "noBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "noReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redeemPool"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[outcome: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "split"
  ): TypedContractMethod<
    [collateralAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapNoForYes"
  ): TypedContractMethod<
    [noIn: BigNumberish, minYesOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapYesForNo"
  ): TypedContractMethod<
    [yesIn: BigNumberish, minNoOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "winningOutcome"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesReserve"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "Merge"
  ): TypedContractEvent<
    MergeEvent.InputTuple,
    MergeEvent.OutputTuple,
    MergeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolRedeemed"
  ): TypedContractEvent<
    PoolRedeemedEvent.InputTuple,
    PoolRedeemedEvent.OutputTuple,
    PoolRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Resolved"
  ): TypedContractEvent<
    ResolvedEvent.InputTuple,
    ResolvedEvent.OutputTuple,
    ResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Split"
  ): TypedContractEvent<
    SplitEvent.InputTuple,
    SplitEvent.OutputTuple,
    SplitEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "Merge(address,uint256,uint256)": TypedContractEvent<
      MergeEvent.InputTuple,
      MergeEvent.OutputTuple,
      MergeEvent.OutputObject
    >;
    Merge: TypedContractEvent<
      MergeEvent.InputTuple,
      MergeEvent.OutputTuple,
      MergeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolRedeemed(address,uint8,uint256,uint256)": TypedContractEvent<
      PoolRedeemedEvent.InputTuple,
      PoolRedeemedEvent.OutputTuple,
      PoolRedeemedEvent.OutputObject
    >;
    PoolRedeemed: TypedContractEvent<
      PoolRedeemedEvent.InputTuple,
      PoolRedeemedEvent.OutputTuple,
      PoolRedeemedEvent.OutputObject
    >;

    "Redeemed(address,uint8,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "Resolved(uint8)": TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;
    Resolved: TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;

    "Split(address,uint256,uint256)": TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;
    Split: TypedContractEvent<
      SplitEvent.InputTuple,
      SplitEvent.OutputTuple,
      SplitEvent.OutputObject
    >;

    "Swap(address,uint8,uint256,uint8,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
